### ISSUE TITLE
copy-pasting several lines at once fails when pasting from context menu

### ISSUE THREAD

**Issue by berger-n** [silevis/reactgrid#250] opened 2023-10-19 13:08 UTC
**Describe the bug**
Copy-pasting several lines at once fails when pasting from context menu.

**Current behavior**
Using CTRL-c then CTRL-v after selecting multiple lines works, whereas using *Paste* from the context menu fails.

**Expected behavior**
*Copy* then *Paste* from the context menu should behave the same as CTRL-c then CTRL-v.

**Screenshots or gifs**
see https://reactgrid.com/docs/4.0/2-implementing-core-features/5-context-menu/ (bottom of the page)

![simplescreenrecorder-2023-10-19_15 04 23 mkv](https://github.com/silevis/reactgrid/assets/33383857/8bbf8446-c54f-4f73-a892-099dab5f52ad)

**Your environment details**
 - Device: desktop
 - OS: Debian (LMDE 5)
 - Browser: Chrome

**Comment by DLowHP** [comment] 2023-10-25 09:49
Hi! I opened the same example in the docs but I couldn't reproduce the error, are you sure there's nothing blocking the code or it has been modified?

**Comment by berger-n** [comment] 2023-10-25 11:53
happens in incognito/private browsing as well, using Chrome 118.0.5993.70, on the last example of the page, right after it's loaded I mean without any modification https://reactgrid.com/docs/4.0/2-implementing-core-features/5-context-menu/, I just have to consent to clipboard access the first time I paste:

![simplescreenrecorder-2023-10-25_13 44 35 mkv](https://github.com/silevis/reactgrid/assets/33383857/cc34a5c2-1f14-4f22-adc7-31339cd5a94c)

---

interestingly in Firefox 119.0 there's no error in console because there's an alert saying it's not supported:

![simplescreenrecorder-2023-10-25_13 51 54 mkv](https://github.com/silevis/reactgrid/assets/33383857/c831d3a5-6a1d-4238-b054-4db9c37b6c3f)

**Comment by qiufeihong2018** [comment] 2023-10-26 06:23
@DLowHP Using the newline character "\n" to split will result in an empty string.

<img width="1390" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/1ef39d3c-e85f-4ed5-b986-e5e0c7b540e6">

<img width="1443" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/9e0a4fbb-f6ab-4499-b7f7-2da907d18073">

I've fixed it and it seems to be resolved. Please help me merge it.
https://github.com/silevis/reactgrid/pull/256

![chrome-capture-2023-9-26 (2)](https://github.com/silevis/reactgrid/assets/36500514/ab0b699a-7dae-4d34-bc40-65ba4a75cf45)

**Comment by DLowHP** [comment] 2023-11-02 13:59
The fix has been merged with #256, I'll close this issue.

**Closed as completed by DLowHP** 2023-11-02 13:59 UTC
