### ISSUE TITLE
 adding a clickable select-all button

### ISSUE THREAD

**Issue by Prathibha-SuryaSoft** [silevis/reactgrid#155] opened 2023-02-17 05:25 UTC
**Describe the bug**
need to add a button or a cell, onClick of it which will be selecting all the cells in the reactGrid

**Comment by alonshmiel** [comment] 2023-03-19 16:37
It's not a bug but question about implementation:

You can add a checkbox cell for every row using:
https://reactgrid.com/docs/4.0/4-cell-templates/2-CheckboxCell/

And a master checkbox (for example: above the table) that re-renders the rows of react-grid with the desired value of each checkbox.

**Comment by alon-shmiel-sage** [comment] 2023-04-04 09:14
Hi @Prathibha-SuryaSoft , please close it if my answer makes sense for you..

**Closed as completed** 2023-04-19 05:23 UTC
